# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ashleysheng/Desktop/6.112/as126

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ashleysheng/Desktop/6.112/as126

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ashleysheng/Desktop/6.112/as126/CMakeFiles /Users/ashleysheng/Desktop/6.112/as126//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ashleysheng/Desktop/6.112/as126/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mitscript-release

# Build rule for target.
mitscript-release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mitscript-release
.PHONY : mitscript-release

# fast build rule for target.
mitscript-release/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/build
.PHONY : mitscript-release/fast

#=============================================================================
# Target rules for targets named mitscript-debug

# Build rule for target.
mitscript-debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mitscript-debug
.PHONY : mitscript-debug

# fast build rule for target.
mitscript-debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/build
.PHONY : mitscript-debug/fast

#=============================================================================
# Target rules for targets named all-build

# Build rule for target.
all-build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all-build
.PHONY : all-build

# fast build rule for target.
all-build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all-build.dir/build.make CMakeFiles/all-build.dir/build
.PHONY : all-build/fast

#=============================================================================
# Target rules for targets named clean-build

# Build rule for target.
clean-build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-build
.PHONY : clean-build

# fast build rule for target.
clean-build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-build.dir/build.make CMakeFiles/clean-build.dir/build
.PHONY : clean-build/fast

src/bytecode/lexer.o: src/bytecode/lexer.cpp.o
.PHONY : src/bytecode/lexer.o

# target to build an object file
src/bytecode/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/bytecode/lexer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/bytecode/lexer.cpp.o
.PHONY : src/bytecode/lexer.cpp.o

src/bytecode/lexer.i: src/bytecode/lexer.cpp.i
.PHONY : src/bytecode/lexer.i

# target to preprocess a source file
src/bytecode/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/bytecode/lexer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/bytecode/lexer.cpp.i
.PHONY : src/bytecode/lexer.cpp.i

src/bytecode/lexer.s: src/bytecode/lexer.cpp.s
.PHONY : src/bytecode/lexer.s

# target to generate assembly for a file
src/bytecode/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/bytecode/lexer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/bytecode/lexer.cpp.s
.PHONY : src/bytecode/lexer.cpp.s

src/bytecode/parser.o: src/bytecode/parser.cpp.o
.PHONY : src/bytecode/parser.o

# target to build an object file
src/bytecode/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/bytecode/parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/bytecode/parser.cpp.o
.PHONY : src/bytecode/parser.cpp.o

src/bytecode/parser.i: src/bytecode/parser.cpp.i
.PHONY : src/bytecode/parser.i

# target to preprocess a source file
src/bytecode/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/bytecode/parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/bytecode/parser.cpp.i
.PHONY : src/bytecode/parser.cpp.i

src/bytecode/parser.s: src/bytecode/parser.cpp.s
.PHONY : src/bytecode/parser.s

# target to generate assembly for a file
src/bytecode/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/bytecode/parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/bytecode/parser.cpp.s
.PHONY : src/bytecode/parser.cpp.s

src/bytecode/prettyprinter.o: src/bytecode/prettyprinter.cpp.o
.PHONY : src/bytecode/prettyprinter.o

# target to build an object file
src/bytecode/prettyprinter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/bytecode/prettyprinter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/bytecode/prettyprinter.cpp.o
.PHONY : src/bytecode/prettyprinter.cpp.o

src/bytecode/prettyprinter.i: src/bytecode/prettyprinter.cpp.i
.PHONY : src/bytecode/prettyprinter.i

# target to preprocess a source file
src/bytecode/prettyprinter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/bytecode/prettyprinter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/bytecode/prettyprinter.cpp.i
.PHONY : src/bytecode/prettyprinter.cpp.i

src/bytecode/prettyprinter.s: src/bytecode/prettyprinter.cpp.s
.PHONY : src/bytecode/prettyprinter.s

# target to generate assembly for a file
src/bytecode/prettyprinter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/bytecode/prettyprinter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/bytecode/prettyprinter.cpp.s
.PHONY : src/bytecode/prettyprinter.cpp.s

src/cli.o: src/cli.cpp.o
.PHONY : src/cli.o

# target to build an object file
src/cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/cli.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/cli.cpp.o
.PHONY : src/cli.cpp.o

src/cli.i: src/cli.cpp.i
.PHONY : src/cli.i

# target to preprocess a source file
src/cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/cli.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/cli.cpp.i
.PHONY : src/cli.cpp.i

src/cli.s: src/cli.cpp.s
.PHONY : src/cli.s

# target to generate assembly for a file
src/cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/cli.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/cli.cpp.s
.PHONY : src/cli.cpp.s

src/lexer.o: src/lexer.cpp.o
.PHONY : src/lexer.o

# target to build an object file
src/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/lexer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/lexer.cpp.o
.PHONY : src/lexer.cpp.o

src/lexer.i: src/lexer.cpp.i
.PHONY : src/lexer.i

# target to preprocess a source file
src/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/lexer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/lexer.cpp.i
.PHONY : src/lexer.cpp.i

src/lexer.s: src/lexer.cpp.s
.PHONY : src/lexer.s

# target to generate assembly for a file
src/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/lexer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/lexer.cpp.s
.PHONY : src/lexer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-release.dir/build.make CMakeFiles/mitscript-release.dir/src/parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mitscript-debug.dir/build.make CMakeFiles/mitscript-debug.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... all-build"
	@echo "... clean-build"
	@echo "... mitscript-debug"
	@echo "... mitscript-release"
	@echo "... src/bytecode/lexer.o"
	@echo "... src/bytecode/lexer.i"
	@echo "... src/bytecode/lexer.s"
	@echo "... src/bytecode/parser.o"
	@echo "... src/bytecode/parser.i"
	@echo "... src/bytecode/parser.s"
	@echo "... src/bytecode/prettyprinter.o"
	@echo "... src/bytecode/prettyprinter.i"
	@echo "... src/bytecode/prettyprinter.s"
	@echo "... src/cli.o"
	@echo "... src/cli.i"
	@echo "... src/cli.s"
	@echo "... src/lexer.o"
	@echo "... src/lexer.i"
	@echo "... src/lexer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

